version: '2'
services:    
  psberlioz-timesheet:
    privileged: true
    image: docker.allette.com.au/psberlioz-timesheet:${VERSION}
    environment:
      BERLIOZ_APPDATA: /tmp/jetty/appdata
    stdin_open: true
    volume_driver: convoy-nfs
    volumes:
    - ${VOLUME_NAME}:/tmp/jetty/appdata
    tty: true
    ports:
    - 8080/tcp
    labels:
      io.rancher.container.pull_image: always