psberlioz-review:
  image: docker.allette.com.au/psberlioz-review:${VERSION}
  environment:
    BERLIOZ_APPDATA: /tmp/jetty/appdata
  stdin_open: true
  volumes:
  - ${VOLUME_NAME}:/tmp/jetty/appdata
  tty: true
  ports:
  - 8080/tcp
  labels:
    io.rancher.container.pull_image: always