version: '2'
services:    
  psberlioz-review:
    privileged: true
    image: 001408692910.dkr.ecr.ap-southeast-2.amazonaws.com/pageseeder/reviewer:${VERSION}
    environment:
      BERLIOZ_APPDATA: /tmp/jetty/appdata
    stdin_open: true
    volume_driver: rancher-nfs
    volumes:
    - ${VOLUME_NAME}:/tmp/jetty/appdata
    tty: true
    ports:
    - 8080/tcp
    labels:
      io.rancher.container.pull_image: always